# Generated by Django 3.2.13 on 2022-06-02 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='expimg/')),
                ('gender', models.CharField(max_length=10)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('want_synergy', models.BooleanField()),
                ('collage', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=2000)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
