# Generated by Django 3.2.13 on 2022-06-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frnz_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='interests',
            field=models.ManyToManyField(to='Frnz_Accounts.Interset'),
        ),
    ]
