# Generated by Django 3.2.13 on 2022-06-20 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frnz_Accounts', '0008_remove_friend_request_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 12, 59, 18, 860980)),
        ),
    ]
