# Generated by Django 3.2.13 on 2022-06-20 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frnz_Accounts', '0009_friend_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 13, 0, 9, 460859)),
        ),
    ]
