# Generated by Django 3.2.13 on 2022-06-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frnz_Accounts', '0010_alter_friend_request_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend_request',
        ),
    ]
