# Generated by Django 3.2.13 on 2022-06-20 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frnz_Accounts', '0011_auto_20220620_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='friends',
            field=models.ManyToManyField(related_name='_Frnz_Accounts_user_profile_friends_+', to='Frnz_Accounts.user_profile'),
        ),
        migrations.CreateModel(
            name='Friend_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=datetime.datetime(2022, 6, 20, 13, 4, 59, 349480))),
                ('status', models.BooleanField(default=False)),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Frnz_Accounts.user_profile')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Frnz_Accounts.user_profile')),
            ],
        ),
    ]
